#!/usr/bin/env node

import 'dotenv/config'
import { writeFileSync, existsSync, mkdirSync } from 'fs'
import { execSync } from 'child_process'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'
import chalk from 'chalk'

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = dirname(__dirname)
const envFile = join(projectRoot, '.env')

function isValidIp(ip) {
  const parts = ip.split('.')
  return parts.length === 4 && parts.every(p => {
    const num = parseInt(p)
    return num >= 0 && num <= 255
  })
}

function detectIpAddress() {
  try {
    const result = execSync("hostname -I 2>/dev/null | awk '{print $1}' || curl -sf ifconfig.me 2>/dev/null || echo ''", { stdio: ['pipe', 'pipe', 'pipe'] })
    const ip = result.toString().trim()
    if (ip && isValidIp(ip)) return ip
  } catch {}
  return null
}

function detectClaudeCode(providedPath) {
  if (providedPath && existsSync(providedPath)) {
    return providedPath
  }

  try {
    const which = execSync('which claude 2>/dev/null', { stdio: ['pipe', 'pipe', 'pipe'] })
    const p = which.toString().trim()
    if (p) return p
  } catch {}

  const paths = [
    process.env.CLAUDE_CLI,
    '/usr/local/bin/claude',
    '/usr/local/bin/claude-code',
  ]

  for (const path of paths) {
    if (path && existsSync(path)) return path
  }

  return null
}

async function runSetupWizard() {
  console.log(chalk.cyan(`\n┌─────────────────────────────────────────────────────┐`))
  console.log(chalk.cyan(`│  VPS-CODE-BOT Setup                                  │`))
  console.log(chalk.cyan(`│  Configure your intelligent VPS platform             │`))
  console.log(chalk.cyan(`└─────────────────────────────────────────────────────┘\n`))

  // Skip if already configured
  if (existsSync(envFile) && process.env.BOT_TOKEN && process.env.CHAT_ID) {
    console.log(chalk.gray('Already configured — skipping setup.\n'))
    return
  }

  // Auto-detect everything, no prompts
  const cliArg = process.argv.includes('--claude-cli')
    ? process.argv[process.argv.indexOf('--claude-cli') + 1]
    : null
  let cliPath = (cliArg && cliArg !== '' && cliArg !== '--os') ? cliArg : detectClaudeCode()

  if (cliPath) {
    console.log(chalk.green(`✓ Claude Code CLI: ${cliPath}`))
  } else {
    cliPath = 'claude'
    console.log(chalk.yellow('⚠ Claude Code CLI not found — will use "claude" from PATH'))
  }

  const ipAddress = detectIpAddress() || 'localhost'
  console.log(chalk.green(`✓ Server IP: ${ipAddress}`))

  // Projects directory — must be under vpsbot home for permissions
  const projectsDir = '/home/vpsbot/projects'
  mkdirSync(projectsDir, { recursive: true })
  console.log(chalk.green(`✓ Projects dir: ${projectsDir}`))

  // Preserve existing values from env
  const existingDomain = process.env.DOMAIN || ''
  const existingBotToken = process.env.BOT_TOKEN || ''
  const existingChatId = process.env.CHAT_ID || ''

  // Generate minimal .env — Telegram/Domain/Claude auth configured from menu
  const envLines = [
    '# Auto-generated by VPS-CODE-BOT Setup',
    '# Configure Telegram & Domain from the CLI menu',
    '',
    existingBotToken ? `BOT_TOKEN=${existingBotToken}` : '# BOT_TOKEN=',
    existingChatId ? `CHAT_ID=${existingChatId}` : '# CHAT_ID=',
    existingDomain ? `DOMAIN=${existingDomain}` : `IP_ADDRESS=${ipAddress}`,
    existingDomain ? '' : 'PORT=80',
    `PROJECTS_DIR=${projectsDir}`,
    `CLAUDE_CLI=${cliPath}`,
    `NODE_BIN=${process.env.NODE_BIN || '/usr/bin/node'}`,
    'CODE_SERVER_PASSWORD=changeme',
    'CODE_SERVER_PORT=8080',
    'CADDY_ADMIN_URL=http://localhost:2019',
    'DOCKER_SOCKET=/var/run/docker.sock',
    '',
  ].filter(l => l !== undefined).join('\n')

  writeFileSync(envFile, envLines)
  console.log(chalk.green('✓ Configuration saved\n'))
}

// Run if executed directly
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  runSetupWizard().catch(err => {
    console.error(chalk.red('Error:'), err.message)
    process.exit(1)
  })
}

export { runSetupWizard }
